server:
  port: 8091
spring:
  profiles: dev
  application:
    name: service-core
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://121.41.2.219:3306/yichen_photo?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      validation-timeout: 30000
      max-lifetime: 60000
  redis:
    host: 121.41.2.219
    port: 63792
    database: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: always

jwt:
  clientId: yichen.project
  key: GM43dxXjoaqEHOZ51NDP306qNfmLCPtPGbCKOFfZicM=
  timeout: 6048000 # 10周
com:
  yichen:
    jwt:
      enabled: true
    global:
      exception:
        enabled: true
    redis:
      enabled: true
    file:
      upload-dir: /data/upload/
      tmp-dir: /data/tmp/
      output-dir: /data/output/
      api-key: TIzalHKGKoSLCs23tCxJoFAt_bvNI7nc
      secret-key: nCk5XlcfthMIrnb00AEW_IfuRQcjG5AQ

---
spring:
  profiles:
    active: dev