server:
  port: 8091
spring:
  cloud:
    zookeeper:
      connect-string: 121.41.2.219:2181
  profiles: dev
  application:
    name: service-core
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ENC(5FpHsKlQ9l8uwe63pY3GhBOfGAYfcRCqPstEvuJ5yV8ol8a0oZxLRmOpK9igDvELuRFYqK+AYSwawyDBxx26HZiDUwluN/IQwI1ZOBiRy1BkJk5jNezBpQX6Yo1CyODMFEcT+4TNW1k/ii+3UvZ/8Of0RisGfZyJNdeyhnM70+pE7SKmRtLsVNAeR9ayCaG5fNKyhS/CtKNnikoMtRWBRQv1ej+mccnOxfboTPRO/xcbLGScJZWXcIKh7CvROzWY)
    username: ENC(PO/MxABOlUrFRM1A2D2ziQ==)
    password: ENC(E+exasNSCkNcLunfhmTUsKgf6UK3gl1y)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      validation-timeout: 30000
      max-lifetime: 60000
  redis:
    host: 121.41.2.219
    port: 6379
    database: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: always

jwt:
  clientId: yichen.project
  key: GM43dxXjoaqEHOZ51NDP306qNfmLCPtPGbCKOFfZicM=
  timeout: 6048000 # 10周
com:
  yichen:
    jwt:
      enabled: true
    global:
      exception:
        enabled: true
    redis:
      enabled: true
    file:
      upload-dir: /data/upload/

---
spring:
  profiles:
    active: dev